### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by lucarin91** [lucarin91/PAD-project#1]
- [ ] Syntax check 
- [ ] Gestione dei conflitti user-based
- [ ] Motivare la scelta delle varie librerie e tools nella sezione 5
- [ ] Introdurre una sezione con la descrizione e il comportamento atteso dei test.
